export const foodList = [
  {
    id: "1",
    img: require("../assets/food1.png"),
    Name: "Burger",
    description: "Juicy beef patty with fresh lettuce and tomatoes",
    price: "9.99",
    isLike: false,
  },
  {
    id: "2",
    img: require("../assets/food1.png"),
    Name: "Pizza",
    description: "Delicious cheese and pepperoni on a thin crust",
    price: "12.99",
    isLike: false,
  },
  {
    id: "3",
    img: require("../assets/food1.png"),
    Name: "Sushi",
    description: "Fresh raw fish on a bed of seasoned rice",
    price: "15.99",
    isLike: false,
  },
  {
    id: "4",
    img: require("../assets/food1.png"),
    Name: "Taco",
    description: "Crispy corn tortilla filled with seasoned ground beef",
    price: "8.99",
    isLike: false,
  },
  {
    id: "5",
    img: require("../assets/food1.png"),
    Name: "Pasta",
    description: "Al dente spaghetti with a rich tomato sauce",
    price: "10.99",
    isLike: false,
  },
  {
    id: "6",
    img: require("../assets/food1.png"),
    Name: "Salad",
    description: "Mixed greens with assorted fresh vegetables",
    price: "7.99",
    isLike: false,
  },
  {
    id: "7",
    img: require("../assets/food1.png"),
    Name: "Sushi Roll",
    description: "Sliced raw fish and vegetables wrapped in seaweed",
    price: "9.99",
    isLike: false,
  },
  {
    id: "8",
    img: require("../assets/food1.png"),
    Name: "Chicken Wings",
    description: "Crispy and spicy chicken wings with a side of ranch",
    price: "11.99",
    isLike: false,
  },
  {
    id: "9",
    img: require("../assets/food1.png"),
    Name: "Steak",
    description: "Tender and juicy grilled steak with mashed potatoes",
    price: "19.99",
    isLike: false,
  },
  {
    id: "10",
    img: require("../assets/food1.png"),
    Name: "Fried Rice",
    description: "Stir-fried rice with vegetables and your choice of meat",
    price: "8.99",
    isLike: false,
  },
  {
    id: "11",
    img: require("../assets/food1.png"),
    Name: "Burrito",
    description: "Large flour tortilla filled with beans, rice, and meat",
    price: "9.99",
    isLike: false,
  },
  {
    id: "12",
    img: require("../assets/food1.png"),
    Name: "Sushi Platter",
    description: "Assortment of sushi rolls and sashimi",
    price: "24.99",
    isLike: false,
  },
  {
    id: "13",
    img: require("../assets/food1.png"),
    Name: "Fish and Chips",
    description: "Crispy battered fish with a side of fries",
    price: "13.99",
    isLike: false,
  },
  {
    id: "14",
    img: require("../assets/food1.png"),
    Name: "Pho",
    description: "Vietnamese noodle soup with beef or chicken",
    price: "10.99",
    isLike: false,
  },
  {
    id: "15",
    img: require("../assets/food1.png"),
    Name: "Chicken Caesar Salad",
    description:
      "Grilled chicken on a bed of romaine lettuce with Caesar dressing",
    price: "8.99",
    isLike: false,
  },
  {
    id: "16",
    img: require("../assets/food1.png"),
    Name: "Ramen",
    description: "Japanese noodle soup with various toppings",
    price: "11.99",
    isLike: false,
  },
  {
    id: "17",
    img: require("../assets/food1.png"),
    Name: "Shrimp Scampi",
    description: "Garlic butter shrimp served with pasta",
    price: "14.99",
    isLike: false,
  },
  {
    id: "18",
    img: require("../assets/food1.png"),
    Name: "Chicken Tikka Masala",
    description: "Spicy Indian curry with grilled chicken and rice",
    price: "12.99",
    isLike: false,
  },
  {
    id: "19",
    img: require("../assets/food1.png"),
    Name: "Gyros",
    description: "Greek pita wrap with seasoned meat and tzatziki sauce",
    price: "9.99",
    isLike: false,
  },
  {
    id: "20",
    img: require("../assets/food1.png"),
    Name: "Pad Thai",
    description: "Thai stir-fried noodles with peanuts and lime",
    price: "10.99",
    isLike: false,
  },
];
export const softDrinkList = [
  {
    id: "21",
    img: require("../assets/soft.jpg"),
    Name: "Cola",
    description: "Classic carbonated cola drink",
    price: "1.99",
    isLike: false,
  },
  {
    id: "22",
    img: require("../assets/soft.jpg"),
    Name: "Lemonade",
    description: "Refreshing lemon-flavored drink",
    price: "2.49",
    isLike: false,
  },
  {
    id: "23",
    img: require("../assets/soft.jpg"),
    Name: "Iced Tea",
    description: "Chilled tea served over ice",
    price: "1.79",
    isLike: false,
  },
  {
    id: "24",
    img: require("../assets/soft.jpg"),
    Name: "Orange Soda",
    description: "Sweet and tangy orange-flavored soda",
    price: "2.29",
    isLike: false,
  },
  {
    id: "25",
    img: require("../assets/soft.jpg"),
    Name: "Root Beer",
    description: "Classic root beer with a frothy top",
    price: "2.29",
    isLike: false,
  },
  {
    id: "26",
    img: require("../assets/soft.jpg"),
    Name: "Ginger Ale",
    description: "Sparkling ginger-flavored soft drink",
    price: "1.99",
    isLike: false,
  },
  {
    id: "27",
    img: require("../assets/soft.jpg"),
    Name: "Fruit Punch",
    description: "Fruity and refreshing mixed fruit punch",
    price: "2.49",
    isLike: false,
  },
  {
    id: "28",
    img: require("../assets/soft.jpg"),
    Name: "Grape Soda",
    description: "Sweet grape-flavored carbonated soda",
    price: "2.29",
    isLike: false,
  },
  {
    id: "29",
    img: require("../assets/soft.jpg"),
    Name: "Cream Soda",
    description: "Smooth and creamy vanilla-flavored soda",
    price: "2.29",
    isLike: false,
  },
  {
    id: "30",
    img: require("../assets/soft.jpg"),
    Name: "Seltzer Water",
    description: "Sparkling water with a hint of natural flavor",
    price: "1.79",
    isLike: false,
  },
];
export const snackList = [
  {
    id: "31",
    img: require("../assets/snack.jpg"),
    Name: "Potato Chips",
    description: "Crunchy and savory potato chips",
    price: "1.99",
    isLike: false,
  },
  {
    id: "32",
    img: require("../assets/snack.jpg"),
    Name: "Popcorn",
    description: "Buttery and salty popped corn kernels",
    price: "2.49",
    isLike: false,
  },
  {
    id: "33",
    img: require("../assets/snack.jpg"),
    Name: "Pretzels",
    description: "Crunchy and twisted salted pretzel sticks",
    price: "1.79",
    isLike: false,
  },
  {
    id: "34",
    img: require("../assets/snack.jpg"),
    Name: "Trail Mix",
    description: "Mix of nuts, dried fruits, and chocolate",
    price: "2.29",
    isLike: false,
  },
  {
    id: "35",
    img: require("../assets/snack.jpg"),
    Name: "Granola Bars",
    description: "Nutritious bars made with oats, nuts, and honey",
    price: "2.29",
    isLike: false,
  },
  {
    id: "36",
    img: require("../assets/snack.jpg"),
    Name: "Cheese Crackers",
    description: "Crunchy crackers with a cheesy flavor",
    price: "1.99",
    isLike: false,
  },
  {
    id: "37",
    img: require("../assets/snack.jpg"),
    Name: "Chocolate Bar",
    description: "Creamy milk chocolate bar",
    price: "2.49",
    isLike: false,
  },
  {
    id: "38",
    img: require("../assets/snack.jpg"),
    Name: "Rice Cakes",
    description: "Light and crispy rice cakes",
    price: "1.79",
    isLike: false,
  },
  {
    id: "39",
    img: require("../assets/snack.jpg"),
    Name: "Fruit Snacks",
    description: "Chewy fruit-flavored snacks",
    price: "2.29",
    isLike: false,
  },
  {
    id: "40",
    img: require("../assets/snack.jpg"),
    Name: "Cookies",
    description: "Classic chocolate chip cookies",
    price: "1.79",
    isLike: false,
  },
];
export const sauceList = [
  {
    id: "41",
    img: require("../assets/sauce.jpg"),
    Name: "Ketchup",
    description: "Classic tomato-based condiment",
    price: "0.99",
    isLike: false,
  },
  {
    id: "42",
    img: require("../assets/sauce.jpg"),
    Name: "Mustard",
    description: "Tangy and savory yellow mustard",
    price: "0.99",
    isLike: false,
  },
  {
    id: "43",
    img: require("../assets/sauce.jpg"),
    Name: "Mayonnaise",
    description: "Creamy and rich mayonnaise",
    price: "1.29",
    isLike: false,
  },
  {
    id: "44",
    img: require("../assets/sauce.jpg"),
    Name: "Barbecue Sauce",
    description: "Sweet and smoky barbecue sauce",
    price: "1.49",
    isLike: false,
  },
  {
    id: "45",
    img: require("../assets/sauce.jpg"),
    Name: "Hot Sauce",
    description: "Spicy and flavorful hot sauce",
    price: "1.29",
    isLike: false,
  },
  {
    id: "46",
    img: require("../assets/sauce.jpg"),
    Name: "Soy Sauce",
    description: "Salty and savory soy sauce",
    price: "0.99",
    isLike: false,
  },
  {
    id: "47",
    img: require("../assets/sauce.jpg"),
    Name: "Tartar Sauce",
    description: "Creamy sauce with chopped pickles and onions",
    price: "1.49",
    isLike: false,
  },
  {
    id: "48",
    img: require("../assets/sauce.jpg"),
    Name: "Ranch Dressing",
    description: "Creamy and tangy ranch dressing",
    price: "1.29",
    isLike: false,
  },
  {
    id: "49",
    img: require("../assets/sauce.jpg"),
    Name: "Sriracha Sauce",
    description: "Spicy chili sauce with garlic and vinegar",
    price: "1.29",
    isLike: false,
  },
  {
    id: "50",
    img: require("../assets/sauce.jpg"),
    Name: "Teriyaki Sauce",
    description: "Sweet and savory Japanese-style sauce",
    price: "1.49",
    isLike: false,
  },
];

export const offerAndPromoCode = [
  {
    id: "FOOD123",
    name: "TastyTreats",
    description: "Get 20% off on your next order with code TASTY20",
  },
  {
    id: "YUMMY456",
    name: "YumDelight",
    description:
      "Enjoy a free dessert with every purchase over $30 using code SWEETDEAL",
  },
  {
    id: "DELISH789",
    name: "DelishDine",
    description:
      "Get $10 off on your first order of $50 or more with code FIRST10",
  },
  {
    id: "TASTE987",
    name: "TasteBuds",
    description: "Buy one, get one free on select items using code BOGO21",
  },
  {
    id: "SAVOR654",
    name: "SavorMeals",
    description:
      "Get 15% off on all orders for a limited time with code SAVOR15",
  },
  {
    id: "CRUNCHY321",
    name: "CrunchyBites",
    description:
      "Enjoy a free appetizer with your order over $25 with code APPETIZER",
  },
  {
    id: "YUMTREATS234",
    name: "YumTreats",
    description: "Get $5 off on your next purchase using code YUM5OFF",
  },
  {
    id: "TASTYPIZZA567",
    name: "TastyPizza",
    description: "Get 25% off on all pizzas with code PIZZA25",
  },
  {
    id: "SWEETTOOTH876",
    name: "SweetTooth",
    description:
      "Enjoy a free ice cream cone with every order over $15 using code ICECREAM",
  },
  {
    id: "HEALTHYEATS098",
    name: "HealthyEats",
    description:
      "Get a salad bowl for half price with the purchase of any main dish using code SALAD50",
  },
  {
    id: "HUNGRY202",
    name: "HungryBelly",
    description:
      "Get a free side dish with every meal order using code SIDESFREE",
  },
  {
    id: "TASTYBURGER444",
    name: "TastyBurger",
    description: "Enjoy $3 off on any burger combo using code BURGER3OFF",
  },
  {
    id: "CHEESELOVER777",
    name: "CheeseLover",
    description: "Buy two cheese items and get one free using code CHEESYDEAL",
  },
  {
    id: "SPICYMEALS555",
    name: "SpicyMeals",
    description: "Get 20% off on all spicy dishes with code SPICE20",
  },
  {
    id: "HAPPYHOUR999",
    name: "HappyHour",
    description: "Enjoy happy hour prices all day long with code HAPPY999",
  },
];

export const history = [];
