export const foodList = [
  {
    id: "1",
    img: require("../assets/food1.png"),
    foodName: "Burger",
    description: "Juicy beef patty with fresh lettuce and tomatoes",
    price: "9.99",
  },
  {
    id: "2",
    img: require("../assets/food1.png"),
    foodName: "Pizza",
    description: "Delicious cheese and pepperoni on a thin crust",
    price: "12.99",
  },
  {
    id: "3",
    img: require("../assets/food1.png"),
    foodName: "Sushi",
    description: "Fresh raw fish on a bed of seasoned rice",
    price: "15.99",
  },
  {
    id: "4",
    img: require("../assets/food1.png"),
    foodName: "Taco",
    description: "Crispy corn tortilla filled with seasoned ground beef",
    price: "8.99",
  },
  {
    id: "5",
    img: require("../assets/food1.png"),
    foodName: "Pasta",
    description: "Al dente spaghetti with a rich tomato sauce",
    price: "10.99",
  },
  {
    id: "6",
    img: require("../assets/food1.png"),
    foodName: "Salad",
    description: "Mixed greens with assorted fresh vegetables",
    price: "7.99",
  },
  {
    id: "7",
    img: require("../assets/food1.png"),
    foodName: "Sushi Roll",
    description: "Sliced raw fish and vegetables wrapped in seaweed",
    price: "9.99",
  },
  {
    id: "8",
    img: require("../assets/food1.png"),
    foodName: "Chicken Wings",
    description: "Crispy and spicy chicken wings with a side of ranch",
    price: "11.99",
  },
  {
    id: "9",
    img: require("../assets/food1.png"),
    foodName: "Steak",
    description: "Tender and juicy grilled steak with mashed potatoes",
    price: "19.99",
  },
  {
    id: "10",
    img: require("../assets/food1.png"),
    foodName: "Fried Rice",
    description: "Stir-fried rice with vegetables and your choice of meat",
    price: "8.99",
  },
  {
    id: "11",
    img: require("../assets/food1.png"),
    foodName: "Burrito",
    description: "Large flour tortilla filled with beans, rice, and meat",
    price: "9.99",
  },
  {
    id: "12",
    img: require("../assets/food1.png"),
    foodName: "Sushi Platter",
    description: "Assortment of sushi rolls and sashimi",
    price: "24.99",
  },
  {
    id: "13",
    img: require("../assets/food1.png"),
    foodName: "Fish and Chips",
    description: "Crispy battered fish with a side of fries",
    price: "13.99",
  },
  {
    id: "14",
    img: require("../assets/food1.png"),
    foodName: "Pho",
    description: "Vietnamese noodle soup with beef or chicken",
    price: "10.99",
  },
  {
    id: "15",
    img: require("../assets/food1.png"),
    foodName: "Chicken Caesar Salad",
    description:
      "Grilled chicken on a bed of romaine lettuce with Caesar dressing",
    price: "8.99",
  },
  {
    id: "16",
    img: require("../assets/food1.png"),
    foodName: "Ramen",
    description: "Japanese noodle soup with various toppings",
    price: "11.99",
  },
  {
    id: "17",
    img: require("../assets/food1.png"),
    foodName: "Shrimp Scampi",
    description: "Garlic butter shrimp served with pasta",
    price: "14.99",
  },
  {
    id: "18",
    img: require("../assets/food1.png"),
    foodName: "Chicken Tikka Masala",
    description: "Spicy Indian curry with grilled chicken and rice",
    price: "12.99",
  },
  {
    id: "19",
    img: require("../assets/food1.png"),
    foodName: "Gyros",
    description: "Greek pita wrap with seasoned meat and tzatziki sauce",
    price: "9.99",
  },
  {
    id: "20",
    img: require("../assets/food1.png"),
    foodName: "Pad Thai",
    description: "Thai stir-fried noodles with peanuts and lime",
    price: "10.99",
  },
];
