export const foodList = [
  {
    id: "1",
    img: require("../assets/food1.png"),
    foodName: "Burger",
    description: "Juicy beef patty with fresh lettuce and tomatoes",
    price: "9.99",
    isLike: false,
  },
  {
    id: "2",
    img: require("../assets/food1.png"),
    foodName: "Pizza",
    description: "Delicious cheese and pepperoni on a thin crust",
    price: "12.99",
    isLike: false,
  },
  {
    id: "3",
    img: require("../assets/food1.png"),
    foodName: "Sushi",
    description: "Fresh raw fish on a bed of seasoned rice",
    price: "15.99",
    isLike: false,
  },
  {
    id: "4",
    img: require("../assets/food1.png"),
    foodName: "Taco",
    description: "Crispy corn tortilla filled with seasoned ground beef",
    price: "8.99",
    isLike: false,
  },
  {
    id: "5",
    img: require("../assets/food1.png"),
    foodName: "Pasta",
    description: "Al dente spaghetti with a rich tomato sauce",
    price: "10.99",
    isLike: false,
  },
  {
    id: "6",
    img: require("../assets/food1.png"),
    foodName: "Salad",
    description: "Mixed greens with assorted fresh vegetables",
    price: "7.99",
    isLike: false,
  },
  {
    id: "7",
    img: require("../assets/food1.png"),
    foodName: "Sushi Roll",
    description: "Sliced raw fish and vegetables wrapped in seaweed",
    price: "9.99",
    isLike: false,
  },
  {
    id: "8",
    img: require("../assets/food1.png"),
    foodName: "Chicken Wings",
    description: "Crispy and spicy chicken wings with a side of ranch",
    price: "11.99",
    isLike: false,
  },
  {
    id: "9",
    img: require("../assets/food1.png"),
    foodName: "Steak",
    description: "Tender and juicy grilled steak with mashed potatoes",
    price: "19.99",
    isLike: false,
  },
  {
    id: "10",
    img: require("../assets/food1.png"),
    foodName: "Fried Rice",
    description: "Stir-fried rice with vegetables and your choice of meat",
    price: "8.99",
    isLike: false,
  },
  {
    id: "11",
    img: require("../assets/food1.png"),
    foodName: "Burrito",
    description: "Large flour tortilla filled with beans, rice, and meat",
    price: "9.99",
    isLike: false,
  },
  {
    id: "12",
    img: require("../assets/food1.png"),
    foodName: "Sushi Platter",
    description: "Assortment of sushi rolls and sashimi",
    price: "24.99",
    isLike: false,
  },
  {
    id: "13",
    img: require("../assets/food1.png"),
    foodName: "Fish and Chips",
    description: "Crispy battered fish with a side of fries",
    price: "13.99",
    isLike: false,
  },
  {
    id: "14",
    img: require("../assets/food1.png"),
    foodName: "Pho",
    description: "Vietnamese noodle soup with beef or chicken",
    price: "10.99",
    isLike: false,
  },
  {
    id: "15",
    img: require("../assets/food1.png"),
    foodName: "Chicken Caesar Salad",
    description:
      "Grilled chicken on a bed of romaine lettuce with Caesar dressing",
    price: "8.99",
    isLike: false,
  },
  {
    id: "16",
    img: require("../assets/food1.png"),
    foodName: "Ramen",
    description: "Japanese noodle soup with various toppings",
    price: "11.99",
    isLike: false,
  },
  {
    id: "17",
    img: require("../assets/food1.png"),
    foodName: "Shrimp Scampi",
    description: "Garlic butter shrimp served with pasta",
    price: "14.99",
    isLike: false,
  },
  {
    id: "18",
    img: require("../assets/food1.png"),
    foodName: "Chicken Tikka Masala",
    description: "Spicy Indian curry with grilled chicken and rice",
    price: "12.99",
    isLike: false,
  },
  {
    id: "19",
    img: require("../assets/food1.png"),
    foodName: "Gyros",
    description: "Greek pita wrap with seasoned meat and tzatziki sauce",
    price: "9.99",
    isLike: false,
  },
  {
    id: "20",
    img: require("../assets/food1.png"),
    foodName: "Pad Thai",
    description: "Thai stir-fried noodles with peanuts and lime",
    price: "10.99",
    isLike: false,
  },
];

export const offerAndPromoCode = [
  {
    id: "FOOD123",
    name: "TastyTreats",
    description: "Get 20% off on your next order with code TASTY20",
  },
  {
    id: "YUMMY456",
    name: "YumDelight",
    description:
      "Enjoy a free dessert with every purchase over $30 using code SWEETDEAL",
  },
  {
    id: "DELISH789",
    name: "DelishDine",
    description:
      "Get $10 off on your first order of $50 or more with code FIRST10",
  },
  {
    id: "TASTE987",
    name: "TasteBuds",
    description: "Buy one, get one free on select items using code BOGO21",
  },
  {
    id: "SAVOR654",
    name: "SavorMeals",
    description:
      "Get 15% off on all orders for a limited time with code SAVOR15",
  },
  {
    id: "CRUNCHY321",
    name: "CrunchyBites",
    description:
      "Enjoy a free appetizer with your order over $25 with code APPETIZER",
  },
  {
    id: "YUMTREATS234",
    name: "YumTreats",
    description: "Get $5 off on your next purchase using code YUM5OFF",
  },
  {
    id: "TASTYPIZZA567",
    name: "TastyPizza",
    description: "Get 25% off on all pizzas with code PIZZA25",
  },
  {
    id: "SWEETTOOTH876",
    name: "SweetTooth",
    description:
      "Enjoy a free ice cream cone with every order over $15 using code ICECREAM",
  },
  {
    id: "HEALTHYEATS098",
    name: "HealthyEats",
    description:
      "Get a salad bowl for half price with the purchase of any main dish using code SALAD50",
  },
  {
    id: "HUNGRY202",
    name: "HungryBelly",
    description:
      "Get a free side dish with every meal order using code SIDESFREE",
  },
  {
    id: "TASTYBURGER444",
    name: "TastyBurger",
    description: "Enjoy $3 off on any burger combo using code BURGER3OFF",
  },
  {
    id: "CHEESELOVER777",
    name: "CheeseLover",
    description: "Buy two cheese items and get one free using code CHEESYDEAL",
  },
  {
    id: "SPICYMEALS555",
    name: "SpicyMeals",
    description: "Get 20% off on all spicy dishes with code SPICE20",
  },
  {
    id: "HAPPYHOUR999",
    name: "HappyHour",
    description: "Enjoy happy hour prices all day long with code HAPPY999",
  },
];
